charon {
    filelog {
        strongswan {
            path = /var/log/strongswan.log
            default = 1
            cfg = 2
            append = no
            flush_line = yes
            ike_name = yes
        }
    }
    syslog {
    }
}
