
[volte_ims]
exten => _.,1,Noop(Incoming call from ${CALLERID(num)})
same => n,Progress()
same => n,Set(FILE(/logs/calls.txt,,,a)=Call from ${CALLERID(num)} at ${STRFTIME(${EPOCH},,%Y-%m-%d-%H:%M:%S)})
same => n,Set(EMAILBODY=${BASE64_ENCODE(You have received a call from ${CALLERID(num)} at ${STRFTIME(${EPOCH},,%Y-%m-%d-%H:%M:%S)})})
same => n,TrySystem(/usr/local/bin/send_notification.py TELEGRAM_ADDRESS '${EMAILBODY}' &)
same => n,WaitForPrecondition(10,2000)
same => n,Ringing()
same => n,Dial(PJSIP/6000)
same => n,Hangup()

[volte_ims_msg]
exten => _.,1,Noop(Incoming SMS from ${MESSAGE(from)} ${MESSAGE(body)})
same => n,Set(NL=${BASE64_DECODE(Cg==)})
same => n,Set(FILE(/logs/messages.txt,,,a)=Message from ${MESSAGE(from)} at ${STRFTIME(${EPOCH},,%Y-%m-%d-%H:%M:%S)}:${NL}${MESSAGE(body)}${NL}===============================================${NL}${NL})
same => n,Set(EMAILBODY=${BASE64_ENCODE(You have received an SMS from ${MESSAGE(from)} at ${STRFTIME(${EPOCH},,%Y-%m-%d-%H:%M:%S)}:${NL}${NL}${MESSAGE(body)})})
same => n,TrySystem(/usr/local/bin/send_notification.py TELEGRAM_ADDRESS '${EMAILBODY}' &)
same => n,MessageSend(pjsip:6000,${MESSAGE(from)},sip:6000@YOUR_DOMAIN)

[from-sip]
exten => _.,1,Noop(Outgoing call to ${EXTEN})
same => n,Set(FILE(/logs/calls.txt,,,a)=Call to ${EXTEN} at ${STRFTIME(${EPOCH},,%Y-%m-%d-%H:%M:%S)})
same => n,Set(EMAILBODY=${BASE64_ENCODE(You have placed a call to ${EXTEN} at ${STRFTIME(${EPOCH},,%Y-%m-%d-%H:%M:%S)})})
same => n,TrySystem(/usr/local/bin/send_notification.py TELEGRAM_ADDRESS '${EMAILBODY}' &)
same => n,Dial(PJSIP/${EXTEN}@volte_ims)
same => n,Hangup()

[msg-from-sip]
exten => _.,1,Noop(Outgoing SMS to ${MESSAGE(to)} ${MESSAGE(body)})
same => n,Set(NL=${BASE64_DECODE(Cg==)})
same => n,Set(FILE(/logs/messages.txt,,,a)=Message to ${MESSAGE(to)} at ${STRFTIME(${EPOCH},,%Y-%m-%d-%H:%M:%S)}:${NL}${MESSAGE(body)}${NL}===============================================${NL}${NL})
same => n,Set(EXTEN=${CUT(CUT(MESSAGE(to),@,1),:,2)})
same => n,Set(EMAILBODY=${BASE64_ENCODE(You have sent an SMS to ${EXTEN} at ${STRFTIME(${EPOCH},,%Y-%m-%d-%H:%M:%S)}:${NL}${NL}${MESSAGE(body)})})
same => n,TrySystem(/usr/local/bin/send_notification.py TELEGRAM_ADDRESS '${EMAILBODY}' &)
same => n,MessageSend(pjsip:volte_ims/${EXTEN}@volte_ims,sip:YOUR_MSISDN@ims.mnc001.mcc262.3gppnetwork.org,sip:${EXTEN}@volte_ims)
