[global]
type=global
allow_sending_180_after_183=yes

[system]
type=system
timer_t1=2000

; ====== SIP listener
[transport-tls-sip]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=/etc/asterisk/certificate.crt
priv_key_file=/etc/asterisk/certificate.key
;cipher=ADH-AES256-SHA,ADH-AES128-SHA
method=tlsv1_2
domain=YOUR_DOMAIN
local_net=172.21.0.0/16
external_media_address=YOUR_DOMAIN
external_signaling_address=YOUR_DOMAIN


;===============ENDPOINT TEMPLATES

[endpoint-basic-sip](!)
type=endpoint
allow=all
media_encryption=sdes
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[auth-userpass-sip](!)
type=auth
auth_type=userpass

[aor-normal-sip](!)
type=aor
max_contacts=3

;===============EXTENSION 6000

[6000](endpoint-basic-sip)
auth=auth-sip
aors=6000
callerid=undefined <YOUR_MSISDN>
context=from-sip
message_context = msg-from-sip

[auth-sip](auth-userpass-sip)
password=SIP_PASSWORD
username=6000


[6000](aor-normal-sip)

;===============VoLTE

[volte_ims]
type=transport
protocol=tcp
bind=[::]:5060
bind_interface=ipsec0
sec_port_c_min=40000
sec_port_c_max=44999
sec_port_s_min=50000
sec_port_s_max=54999
p_access_network_info=IEEE-802.11\;i-wlan-node-id=mywifi
sec_encryption=yes

[volte_ims]
type=registration
transport=volte_ims
outbound_auth=volte_ims
imei=35876110-025850-3
server_uri=sip:ims.mnc001.mcc262.3gppnetwork.org
client_uri=sip:262011234567890@ims.mnc001.mcc262.3gppnetwork.org
retry_interval=30
fatal_retry_interval=30
max_retries=999999999
expiration=600000
volte=yes
manual_register=yes
endpoint=volte_ims
receive_sms=yes

[volte_ims]
type=endpoint
user_eq_phone=on
transport=volte_ims
context=volte_ims
message_context=volte_ims_msg
disallow=all
allow=amr
bw_value=41
outbound_auth=volte_ims
aors=volte_ims
rewrite_contact=yes
from_domain=ims.mnc001.mcc262.3gppnetwork.org
from_user=YOUR_MSISDN
volte=yes
dedicated_bearer_up=yes
100rel=peer_supported
moh_passthrough=yes
direct_media=no
smsc_uri=sip:YOUR_SMSC@ims.mnc001.mcc262.3gppnetwork.org

[volte_ims]
type=auth
auth_type=ims_aka
username=262011234567890@ims.mnc001.mcc262.3gppnetwork.org
usim_ami=yes

[volte_ims]
type=aor
contact=sip:262011234567890@ims.mnc001.mcc262.3gppnetwork.org
max_contacts=1

[volte_ims]
type=identify
endpoint=volte_ims
match=2a01:598:408:3003::11

[ims.mnc001.mcc262.3gppnetwork.org]
type=resolve
ip=2a01:598:408:3003::11
transport=volte_ims

[smsoip.ims.mnc001.mcc262.3gppnetwork.org]
type=resolve
ip=2a01:598:408:3003::11
transport=volte_ims


